name: terra
description: Generate codes
inputs:
  terra-ref:
    description: The terra repo ref
    required: true
    default: "main"

  target-repo:
    description: The pull request target repo
    required: true
    default: "AgoraIO-Extensions/Agora-Flutter-SDK"

  target-branch:
    description: The pull request target branch
    required: true
    default: "main"

  target-path:
    description: The path to generate codes, if set, will skip clone & pr

  target-branch-name-surffix:
    description: The surffix of the branch name, e.g., if terra-update, the branch name become main-terra-update
    required: true
    default: "terra-update"

  pull-request-title:
    description: The title of the pull request
    required: true
    default: "[AUTO] Generate code by terra"

  config:
    description: The config for terra
    required: true
    default: "terra_config.yaml"

  output-dir:
    description: The output dir
    required: true
    default: "lib/src"

  export-file-path:
    description: The export file path
    required: true
    default: "lib/agora_rtc_engine.dart"

  pre-pr-command:
    description: The command before pr

  github-token:
    description: The github token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout terra
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.github-token }}
        repository: AgoraIO-Extensions/terra
        ref: ${{ inputs.terra-ref }}
        path: terra

    - name: Checkout build project
      if: ${{ !inputs.target-path }}
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.github-token }}
        repository: ${{ inputs.target-repo }}
        ref: ${{ inputs.target-branch }}
        path: ${{ inputs.target-repo }}

    - uses: actions/setup-node@v3
      with:
        node-version: "16.x"

    - name: Setup
      run: |
        brew install coreutils
      shell: bash

    - name: Run terra
      run: |
        set -x

        export PATH="/usr/local/opt/llvm/bin:$PATH"

        npm install

        if [[ -n "${{ inputs.target-path }}" ]]; then
          TARGET_PATH="${{ inputs.target-path }}"
        else
          TARGET_PATH="${{ inputs.target-repo }}"
        fi

        ROOT_PATH="${{ github.workspace }}/${TARGET_PATH}"
        npm run build -- render-legacy \
          --config "${ROOT_PATH}/${{ inputs.config }}" \
          --output-dir="${ROOT_PATH}/${{ inputs.output-dir }}" \
          --export-file-path="${ROOT_PATH}/${{ inputs.export-file-path }}"
      working-directory: terra/terra-cli
      shell: bash

    - name: Run command before pr
      if: ${{ inputs.pre-pr-command }}
      run: ${{ inputs.pre-pr-command }}
      working-directory: ${{ inputs.target-repo }}
      shell: bash

    - name: Create pull request
      if: ${{ !inputs.target-path }}
      uses: ./.github/actions/pr
      with:
        target-repo: ${{ inputs.target-repo }}
        target-branch: ${{ inputs.target-branch }}
        target-branch-name-surffix: ${{ inputs.target-branch-name-surffix }}
        pull-request-title: ${{ inputs.pull-request-title }}
        github-token: ${{ inputs.github-token }}
