name: terra
description: Generate codes.

inputs:
  github-token:
    description: >
      GITHUB_TOKEN (permissions contents: write and pull-requests: write) or a repo scoped Personal Access Token (PAT).
    required: true

  target-repo:
    description: Relative path under GITHUB_WORKSPACE to the repository.

  target-branch:
    description: Sets the pull request base branch.

  terra-ref:
    description: The ref of terra repo will be used.
    required: true
    default: "main"

  config:
    description: The terra-cli yaml config file path, e.g., terra-config.yaml.
    required: true

  output-dir:
    description: The output directory.
    required: true

  export-file-path:
    description: The export file path of iris_doc command.
    required: true

  pre-pr-command:
    description: The bash script will run before create pull request.

outputs:
  configuration:
    description: The content of the terra-cli yaml config file.
    value: ${{ steps.terra.outputs.configuration }}

runs:
  using: composite
  steps:
    - name: Checkout terra
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.github-token }}
        repository: AgoraIO-Extensions/terra_archive
        ref: ${{ inputs.terra-ref }}
        path: terra

    - name: Checkout target repo
      if: ${{ inputs.target-repo }}
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.github-token }}
        repository: ${{ inputs.target-repo }}
        ref: ${{ inputs.target-branch }}
        path: ${{ inputs.target-repo }}

    - uses: actions/setup-node@v3
      with:
        node-version: "16.x"

    - name: Setup
      if: ${{ runner.os == 'macOS' }}
      run: |
        brew install coreutils
        brew install llvm@15
      shell: bash

    - name: Run terra
      id: terra
      run: |
        set -x

        export PATH="/usr/local/opt/llvm@15/bin:$PATH"

        npm install

        ROOT_PATH="${{ github.workspace }}"

        if [[ -n "${{ inputs.target-repo }}" ]]; then
          TARGET_PATH="${ROOT_PATH}/${{ inputs.target-repo }}"
        else
          TARGET_PATH="${ROOT_PATH}"
        fi

        npm run build -- render-legacy \
          --config ${TARGET_PATH}/${{ inputs.config }} \
          --output-dir=${TARGET_PATH}/${{ inputs.output-dir }} \
          --export-file-path=${TARGET_PATH}/${{ inputs.export-file-path }}

        {
          echo 'configuration<<EOF'
          cat "${TARGET_PATH}/${{ inputs.config }}"
          echo EOF
        } >> "$GITHUB_OUTPUT"
      working-directory: terra/terra-cli
      shell: bash

    - name: Run command before pr
      if: ${{ inputs.pre-pr-command }}
      run: ${{ inputs.pre-pr-command }}
      working-directory: ${{ inputs.target-repo }}
      shell: bash

    - name: Create pull request
      if: ${{ inputs.target-branch }}
      uses: AgoraIO-Extensions/actions/.github/actions/pr@main
      with:
        github-token: ${{ inputs.github-token }}
        target-repo: ${{ inputs.target-repo }}
        target-branch: ${{ inputs.target-branch }}
        target-branch-name-surffix: terra-update
        pull-request-title: |
          [AUTO] Generate codes by terra
        pull-request-body: |
          Terra configuration:

          ${{ steps.terra.outputs.configuration }} 
