name: doc
description: Generate comments.

inputs:
  github-token:
    description: >
      GITHUB_TOKEN (permissions contents: write and pull-requests: write) or a repo scoped Personal Access Token (PAT).
    required: true

  target-repo:
    description: Relative path under GITHUB_WORKSPACE to the repository.

  target-branch:
    description: Sets the pull request base branch.

  iris-doc-ref:
    description: The ref of terra repo will be used.
    required: true
    default: "main"

  config:
    description: The path of the `fmt.json` file.
    required: true

  language:
    description: The name of programming language.
    required: true

  base-template-url:
    description: The github release url of the template file, which allow set multiple times, the json will be merge in file order.
    required: true

  base-template-url2:
    description: The extra input of base-template-url.

  export-file-path:
    description: The path of the export file.
    required: true

  pre-pr-command:
    description: The bash script will run before create pull request.

runs:
  using: composite
  steps:
    - name: Checkout iris-doc
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.github-token }}
        repository: littleGnAl/iris-doc
        ref: ${{ inputs.iris-doc-ref }}
        path: iris-doc

    - name: Checkout target repo
      if: ${{ inputs.target-repo }}
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.github-token }}
        repository: ${{ inputs.target-repo }}
        ref: ${{ inputs.target-branch }}
        path: ${{ inputs.target-repo }}

    - uses: subosito/flutter-action@v1
      if: ${{ inputs.language == 'dart' }}
      with:
        flutter-version: "3.0.0"

    - uses: actions/setup-node@v3
      if: ${{ inputs.language == 'ts' }}
      with:
        node-version: "16.x"

    - name: Run iris-doc
      run: |
        set -x

        python3 -m pip install -r requirements.txt

        BASE_TEMPLATE_URL="${{ inputs.base-template-url }}"
        MERGE_TEMPLATE_URL="${{ inputs.base-template-url2 }}"
        TEMPLATE_URL_ARGS="--template-url=${BASE_TEMPLATE_URL}"

        if [[ -n "${MERGE_TEMPLATE_URL}" ]]; then
          TEMPLATE_URL_ARGS="${TEMPLATE_URL_ARGS} --template-url=${MERGE_TEMPLATE_URL}"
        fi

        ROOT_PATH="${{ github.workspace }}"

        if [[ -n "${{ inputs.target-repo }}" ]]; then
          TARGET_PATH="${ROOT_PATH}/${{ inputs.target-repo }}"
        else
          TARGET_PATH="${ROOT_PATH}"
        fi

        EXPORT_FILE_PATH="${TARGET_PATH}/${{ inputs.export-file-path }}"
        python3 iris_doc.py --config="${ROOT_PATH}/iris-doc/${{ inputs.config }}" \
          --language="${{ inputs.language }}" \
          --export-file-path=${EXPORT_FILE_PATH} \
          ${TEMPLATE_URL_ARGS}
      working-directory: iris-doc
      shell: bash

    - name: Run command before pr
      if: ${{ inputs.pre-pr-command }}
      run: ${{ inputs.pre-pr-command }}
      working-directory: ${{ inputs.target-repo }}
      shell: bash

    - name: Create pull request
      if: ${{ inputs.target-branch }}
      uses: AgoraIO-Extensions/actions/.github/actions/pr@main
      with:
        github-token: ${{ inputs.github-token }}
        target-repo: ${{ inputs.target-repo }}
        target-branch: ${{ inputs.target-branch }}
        target-branch-name-surffix: doc-update
        pull-request-title: |
          [AUTO] Generate comments by iris-doc
        pull-request-body: |
          Doc source:
          
          ${{ inputs.base-template-url }}
