name: doc
description: Generate comments
inputs:
  iris-doc-ref:
    description: The iris-doc repo ref
    required: true
    default: "main"

  target-repo:
    description: The pull request target repo
    required: true
    default: "AgoraIO-Extensions/Agora-Flutter-SDK"

  target-branch:
    description: The pull request target branch
    required: true
    default: "main"

  target-path:
    description: The path to generate comments, if set, will skip clone & pr

  target-branch-name-surffix:
    description: The surffix of the branch name, e.g., if doc-update, the branch name become main-doc-update
    required: true
    default: "doc-update"

  pull-request-title:
    description: The title of the pull request
    required: true
    default: "[AUTO] Generate comments by iris-doc"

  config:
    description: The language config
    required: true
    default: "fmt_config/fmt_dart.yaml"

  language:
    description: The language
    required: true
    default: "dart"

  base-template-url:
    description: The base template url
    required: true
    default: "https://github.com/AgoraIO/agora_doc_source/releases/download/main/flutter_ng_json_template_en.json"

  merge-template-url:
    description: The template url to merge
    default: ""

  export-file-path:
    description: The export file path
    required: true
    default: "lib/agora_rtc_engine.dart"

  github-token:
    description: The github token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout iris-doc
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.github-token }}
        repository: littleGnAl/iris-doc
        ref: ${{ inputs.iris-doc-ref }}
        path: iris-doc

    - name: Checkout build project
      if: ${{ !inputs.target-path }}
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.github-token }}
        repository: ${{ inputs.target-repo }}
        ref: ${{ inputs.target-branch }}
        path: ${{ inputs.target-repo }}

    - uses: subosito/flutter-action@v1
      if: ${{ inputs.language == 'dart' }}
      with:
        flutter-version: "3.0.0"

    - uses: actions/setup-node@v3
      if: ${{ inputs.language == 'ts' }}
      with:
        node-version: "16.x"

    - name: Run iris-doc
      run: |
        set -x

        python3 -m pip install -r requirements.txt

        BASE_TEMPLATE_URL="${{ inputs.base-template-url }}"
        MERGE_TEMPLATE_URL="${{ inputs.merge-template-url }}"
        TEMPLATE_URL_ARGS="--template-url=${BASE_TEMPLATE_URL}"

        if [[ -n "${MERGE_TEMPLATE_URL}" ]]; then
          TEMPLATE_URL_ARGS="${TEMPLATE_URL_ARGS} --template-url=${MERGE_TEMPLATE_URL}"
        fi

        if [[ -n "${{ inputs.target-path }}" ]]; then
          TARGET_PATH="${{ inputs.target-path }}"
        else
          TARGET_PATH="${{ inputs.target-repo }}"
        fi

        ROOT_PATH="${{ github.workspace }}"
        EXPORT_FILE_PATH=${ROOT_PATH}/${TARGET_PATH}/${{ inputs.export-file-path }}
        python3 iris_doc.py --config="${ROOT_PATH}/iris-doc/${{ inputs.config }}" --language="${{ inputs.language }}" --export-file-path=${EXPORT_FILE_PATH} ${TEMPLATE_URL_ARGS}
      working-directory: iris-doc
      shell: bash

    - name: Create pull request
      if: ${{ !inputs.target-path }}
      uses: AgoraIO-Extensions/actions/.github/actions/pr@main
      with:
        target-repo: ${{ inputs.target-repo }}
        target-branch: ${{ inputs.target-branch }}
        target-branch-name-surffix: ${{ inputs.target-branch-name-surffix }}
        pull-request-title: ${{ inputs.pull-request-title }}
        pull-request-body: |
          doc source: ${{ inputs.base-template-url }}
        github-token: ${{ inputs.github-token }}
