name: pr
description: Create pull request.

inputs:
  github-token:
    description: >
      GITHUB_TOKEN (permissions contents: write and pull-requests: write) or a repo scoped Personal Access Token (PAT).
    required: true

  target-repo:
    description: Relative path under GITHUB_WORKSPACE to the repository.

  target-branch:
    description: Sets the pull request base branch.
    required: true

  target-branch-name-surffix:
    description: The surffix of the branch name, e.g., if terra-update, the branch name become main-terra-update
    required: true

  pull-request-title:
    description: The title of the pull request.
    required: true

  pull-request-body:
    description: The body of the pull request.
    required: true
    default: ""

  add-paths:
    description: >
      A comma or newline-separated list of file paths to commit.
      Paths should follow git's pathspec syntax.
      If no paths are specified, all new and modified files are added.
      See Add specific paths.

runs:
  using: composite
  steps:
    - name: Create timestamp
      id: timestamp
      run: |
        echo "timestamp=$(date +%Y%m%d%H%M)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ inputs.github-token }}
        path: ${{ inputs.target-repo }}
        add-paths: ${{ inputs.add-paths }}
        commit-message: ${{ inputs.pull-request-title }}
        branch: "${{ inputs.target-branch }}-${{ inputs.target-branch-name-surffix }}-${{ steps.timestamp.outputs.timestamp }}"
        delete-branch: true
        base: ${{ inputs.target-branch }}
        title: ${{ inputs.pull-request-title }}
        body: ${{ inputs.pull-request-body }}
        labels: ci:${{ inputs.target-branch-name-surffix }}
