name: dep
description: Get dependencies.

inputs:
  dependencies-content:
    description: The content of dependencies.
    required: true

outputs:
  matches:
    description: Dependencies matches
    value: ${{ steps.dep.outputs.matches }}

runs:
  using: composite
  steps:

    - name: Get dependencies
      id: dep
      run: |
        set -x
        matches=$(python3 dep.py "${{ inputs.dependencies-content }}" | jq -c . | jq -Rr @json)
        echo "matches=$matches" >> "$GITHUB_OUTPUT"
      working-directory: ${{ github.action_path }}
      shell: bash
