name: dep
description: Update dependencies.

inputs:
  github-token:
    description: >
      GITHUB_TOKEN (permissions contents: write and pull-requests: write) or a repo scoped Personal Access Token (PAT).
    required: true

  target-repo:
    description: Relative path under GITHUB_WORKSPACE to the repository.

  target-branch:
    description: Sets the pull request base branch.

  dependencies-content:
    description: The content of dependencies.
    required: true

  target-files:
    description: The files to update dependencies
    required: true

outputs:
  matches:
    description: Dependencies matches
    value: ${{ steps.dep.outputs.matches }}

runs:
  using: composite
  steps:
    - name: Checkout target repo
      if: ${{ inputs.target-repo }}
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.github-token }}
        repository: ${{ inputs.target-repo }}
        ref: ${{ inputs.target-branch }}
        path: ${{ inputs.target-repo }}

    - name: Update dependencies
      id: dep
      run: |
        set -x

        ROOT_PATH="${{ github.workspace }}"

        if [[ -n "${{ inputs.target-repo }}" ]]; then
          TARGET_PATH="${ROOT_PATH}/${{ inputs.target-repo }}"
        else
          TARGET_PATH="${ROOT_PATH}"
        fi

        {
          echo 'matches<<EOF'
          python3 dep.py "${{ inputs.dependencies-content }}" "${TARGET_PATH}" "${{ inputs.target-files }}"
          echo EOF
        } >> "$GITHUB_OUTPUT"
      working-directory: ${{ github.action_path }}
      shell: bash

    - name: Create pull request
      if: ${{ inputs.target-branch }}
      uses: AgoraIO-Extensions/actions/.github/actions/pr@main
      with:
        github-token: ${{ inputs.github-token }}
        target-repo: ${{ inputs.target-repo }}
        target-branch: ${{ inputs.target-branch }}
        target-branch-name-surffix: dep-update
        pull-request-title: |
          [AUTO] Update dependencies
        pull-request-body: |
          Dependencies content: 
          
          ${{ steps.dep.outputs.matches }}
