name: CDN
description: Upload github release assets to CDN.

inputs:
  upload_cdn_internal_jenkins_hook:
    description: The upload cdn internal jenkins hook
    required: true

  url:
    description: The github release artifact url
    required: true

  release_type:
    description: The release type of CDN
    default: "demo-test"

runs:
  using: composite
  steps:
    - name: CDN Publish
      run: |
        UPLOAD_CDN_INTERNAL_JENKINS_HOOK=${{ inputs.upload_cdn_internal_jenkins_hook }}
        UPLOAD_URL=${{ inputs.url }}
        RELEASE_TYPE=${{ inputs.release_type }}

        curl -X POST ${UPLOAD_CDN_INTERNAL_JENKINS_HOOK} \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -d "{ \"release\": { \"assets\": [ { \"browser_download_url\": \"${UPLOAD_URL}\", \"release_type\": \"${RELEASE_TYPE}\" } ] }}"
      shell: bash
