name: move Package to Shenwang repo

inputs:
  github-email:
    description: GIT_EMAIL from secrets
    required: true
  github-username:
    description: GIT_USERNAME from secrets
    required: true
  github-token:
    description: >
      GITHUB_TOKEN (permissions contents: write and pull-requests: write) or a repo scoped Personal Access Token (PAT).
    required: true
  target-repo:
    description: 'Target repository (e.g., owner/repo)'
    required: true
  target-branch:
    description: 'Target branch to commit to'
    required: true
  pre-command:
    description: The bash script will run before commit.
    required: true

runs:
  using: composite
  steps:
    - name: Checkout the current repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.workspace }}

    - name: Run command before commit
      if: ${{ inputs.pre-command }}
      run: ${{ inputs.pre-command }}
      working-directory: ${{ github.workspace }}
      shell: bash

    - name: Copy package to temp directory
      run: |
        echo "Starting pre hook..."
        cp -r "${{ github.workspace }}" .
        ls
      shell: bash

    - name: Checkout the target repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.target-repo }}
        ref: ${{ inputs.target-branch }}
        token: ${{ inputs.github-token }}

    - name: Configure Git
      run: |
        git config --global user.email "${{ inputs.github-email }}"
        git config --global user.name "${{ inputs.github-username }}"
      shell: bash

    # - name: Commit changes
    #   run: |
    #     git add .
    #     git commit -m "sync package from ${GITHUB_REPOSITORY} to ${{ inputs.target-repo }}"
    #     git push origin ${{ inputs.target-branch }}