name: move Package to Shenwang repo

inputs:
  github-email:
    description: GIT_EMAIL from secrets
    required: true
  github-username:
    description: GIT_USERNAME from secrets
    required: true
  github-token:
    description: >
      GITHUB_TOKEN (permissions contents: write and pull-requests: write) or a repo scoped Personal Access Token (PAT).
    required: true
  target-repo:
    description: 'Target repository (e.g., owner/repo)'
    required: true
  target-branch:
    description: 'Target branch to commit to'
    required: true
  pre-command:
    description: The bash script will run before commit.
    required: true

runs:
  using: composite
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}

    - name: Run command before commit
      if: ${{ inputs.pre-command }}
      run: ${{ inputs.pre-command }}
      shell: bash

    - name: Configure Git and Commit
      run: |
        git config --global user.email "${{ inputs.github-email }}"
        git config --global user.name "${{ inputs.github-username }}"
        git remote add origin ${{ inputs.target-repo }}
        git branch -M ${{ inputs.target-branch }}
        git commit -m "sync package from ${GITHUB_REPOSITORY} to ${{ inputs.target-repo }}"
        git push -u origin ${{ inputs.target-branch }}
      shell: bash
