name: move Package to Shenwang repo

inputs:
  github-email:
    description: GIT_EMAIL from secrets
    required: true
  github-username:
    description: GIT_USERNAME from secrets
    required: true
  github-private-key:
    description: GH_PRIVATE_KEY from secrets
    required: true
  github-token:
    description: >
      GITHUB_TOKEN (permissions contents: write and pull-requests: write) or a repo scoped Personal Access Token (PAT).
    required: true
  source-repo:
    description: 'Source repository (e.g., owner/repo)'
    required: true
  target-repo:
    description: 'Target repository (e.g., owner/repo)'
    required: true
  target-branch:
    description: 'Target branch to commit to'
    required: true
  pre-command:
    description: The bash script will run before commit.
    required: true

runs:
  using: composite
  steps:
    - name: Mirror react-native-agora to Gitee
      uses: guoxianzhe/hub-mirror-action@master
      with:
        src: github/AgoraIO-Extensions
        dst: github/AgoraIO-Extensions
        dst_key: ${{ inputs.github-private-key }}
        dst_token: ${{ inputs.github-token }}
        account_type: org
        clone_style: "ssh"
        force_update: true
        mappings: "${{ inputs.target-repo }}=>${{ inputs.source-repo }}"
        static_list: "${{ inputs.target-repo }}"
        shell_command: |
          git config --global user.email "${{ inputs.github-email }}"
          git config --global user.name "${{ inputs.github-username }}"
          git branch -M ${{ inputs.target-branch }}
          ${{ inputs.pre-command }}
          git add .
          git commit -m '[AUTO]sync to shengwang>> change package'
          git push -u origin ${{ inputs.target-branch }}

