name: move Package to Shenwang repo

inputs:
  github-email:
    description: GIT_EMAIL from secrets
    required: true
  github-username:
    description: GIT_USERNAME from secrets
    required: true
  github-private-key:
    description: GH_PRIVATE_KEY from secrets
    required: true
  github-token:
    description: >
      GITHUB_TOKEN (permissions contents: write and pull-requests: write) or a repo scoped Personal Access Token (PAT).
    required: true
  source-repo:
    description: 'Source repository (e.g., owner/repo)'
    required: true
  target-repo:
    description: 'Target repository (e.g., owner/repo)'
    required: true
  target-branch:
    description: 'Target branch to commit to'
    required: true
  pre-command:
    description: The bash script will run before commit.
    required: true
  create-pr:
    description: 'if need create pr'
    type: boolean
    required: true

runs:
  using: composite
  steps:
    - name: Mirror react-native-agora to Gitee
      uses: guoxianzhe/hub-mirror-action@master
      with:
        src: github/AgoraIO-Extensions
        dst: github/AgoraIO-Extensions
        dst_key: ${{ inputs.github-private-key }}
        dst_token: ${{ inputs.github-token }}
        account_type: org
        cache_path: /github/workspace/hub-mirror-cache
        clone_style: "ssh"
        force_update: true
        mappings: "${{ inputs.source-repo }}=>${{ inputs.target-repo }}"
        static_list: "${{ inputs.source-repo }}"
        shell_command: |
          git config --global user.email "${{ inputs.github-email }}"
          git config --global user.name "${{ inputs.github-username }}"
          git remote -v
          git remote remove origin
          git remote rename github origin
          git checkout --track origin/${{ inputs.target-branch }}
          ${{ inputs.pre-command }}
          if not ${{ inputs.create-pr }} ; then git add . ; fi
          if not ${{ inputs.create-pr }} ; then git commit -m '[AUTO]sync agora to shengwang>> change package' ; fi
          if not ${{ inputs.create-pr }} ; then git push origin ; fi

    - name: Create pull request
      if: ${{ inputs.create-pr }}
      uses: AgoraIO-Extensions/actions/.github/actions/pr@main
      with:
        github-token: ${{ inputs.github-token }}
        target-repo: ${{ github.workspace }}
        target-branch: ${{ inputs.target-branch }}
        target-branch-name-surffix: shengwang-sync-auto
        pull-request-title: |
          [AUTO]sync agora to shengwang>> change package
        pull-request-body: |
          This is an auto-generated PR to sync agora to shengwang
          Please review changes and check the CI status.
          If everything is fine, please merge this PR.
