name: move Package to Shenwang repo

inputs:
  github-email:
    description: GIT_EMAIL from secrets
    required: true
  github-username:
    description: GIT_USERNAME from secrets
    required: true
  github-private-key:
    description: GH_PRIVATE_KEY from secrets
    required: true
  github-token:
    description: >
      GITHUB_TOKEN (permissions contents: write and pull-requests: write) or a repo scoped Personal Access Token (PAT).
    required: true
  source-repo:
    description: 'Source repository (e.g., owner/repo)'
    required: true
  target-repo:
    description: 'Target repository (e.g., owner/repo)'
    required: true
  target-branch:
    description: 'Target branch to commit to'
    required: true
  pre-command:
    description: The bash script will run before commit.
    required: true
  create-pr:
    description: 'if need create pr'
    type: boolean
    required: true

runs:
  using: composite
  steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github-token }}
        repository: ${{ github.repository_owner }}/${{ inputs.target-repo }}

    - name: Configure git
      run: |
        git config --global user.email "${{ inputs.github-email }}"
        git config --global user.name "${{ inputs.github-username }}"
        git config --global push.autoSetupRemote true
      shell: bash

    - name: Add source repo as remote
      run: |
        git remote add agora https://github.com/${{ github.repository_owner }}/${{ inputs.source-repo }}.git
        git fetch agora
      shell: bash

    - name: Rebase source repo onto target repo
      run: |
        git checkout ${{ inputs.target-branch }}
        git rebase agora/${{ github.target-branch }}
      shell: bash

    - name: Push changes to target repo
      run: |
        git push origin ${{ inputs.target-branch }} --force
      shell: bash

    - name: Run pre-command
      run: |
        ${{ inputs.pre-command }}
      shell: bash

    # - name: Commit directly
    #   if: ${{ !inputs.create-pr }}
    #   run: |
    #     ${{ inputs.pre-command }}
    #     git add .
    #     git commit -m '[AUTO]sync agora to shengwang>> change package'
    #     git push --f origin
    #   working-directory: ${{ inputs.source-repo }}
    #   shell: bash

    - name: Create pull request
      if: ${{ inputs.create-pr }}
      uses: AgoraIO-Extensions/actions/.github/actions/pr@sync
      with:
        github-token: ${{ inputs.github-token }}
        target-repo: ${{ inputs.target-repo }}
        target-branch: ${{ inputs.target-branch }}
        target-branch-name-surffix: shengwang-sync-auto
        pull-request-title: |
          [AUTO]sync agora to shengwang>> change package
        pull-request-body: |
          This is an auto-generated PR to sync agora to shengwang
          Please review changes and check the CI status.
          If everything is fine, please merge this PR.
