name: move Package to Shenwang repo

inputs:
  github-email:
    description: GIT_EMAIL from secrets
    required: true
  github-username:
    description: GIT_USERNAME from secrets
    required: true
  github-private-key:
    description: GH_PRIVATE_KEY from secrets
    required: true
  github-token:
    description: >
      GITHUB_TOKEN (permissions contents: write and pull-requests: write) or a repo scoped Personal Access Token (PAT).
    required: true
  source-repo:
    description: 'Source repository (e.g., owner/repo)'
    required: true
  target-repo:
    description: 'Target repository (e.g., owner/repo)'
    required: true
  target-branch:
    description: 'Target branch to commit to'
    required: true
  pre-command:
    description: The bash script will run before commit.
    required: true
  create-pr:
    description: 'if need create pr'
    type: boolean
    required: true

runs:
  using: composite
  steps:
    - name: Checkout source repo
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github-token }}
        repository: ${{ github.repository_owner }}/${{ inputs.source-repo }}
        ref: ${{ github.ref }}
        path: ${{ inputs.source-repo }}

    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github-token }}
        repository: ${{ github.repository_owner }}/${{ inputs.target-repo }}
        path: ${{ inputs.target-repo }}

    - name: Move package
      run: |
        cp -r ${{ inputs.source-repo }}/* ${{ inputs.target-repo }}/
      shell: bash

    - name: run pre-command
      run: |
        ${{ inputs.pre-command }}
        git checkout -b 
        git fetch origin
        if git show-ref --verify --quiet refs/remotes/origin/${{ inputs.target-branch }}; then
            git push origin --delete ${{ inputs.target-branch }}
        fi
        git status
        git checkout -b ${{ inputs.target-branch }}
        git add .
        git commit -m '[AUTO]sync agora to shengwang'
      working-directory: ${{ inputs.target-repo }}
      shell: bash

    # - name: Commit directly
    #   if: ${{ !inputs.create-pr }}
    #   run: |
    #     ${{ inputs.pre-command }}
    #     git add .
    #     git commit -m '[AUTO]sync agora to shengwang>> change package'
    #     git push --f origin
    #   working-directory: ${{ inputs.source-repo }}
    #   shell: bash

    # - name: Create pull request
    #   if: ${{ inputs.create-pr }}
    #   uses: AgoraIO-Extensions/actions/.github/actions/pr@sync
    #   with:
    #     github-token: ${{ inputs.github-token }}
    #     target-repo: ${{ inputs.target-repo }}
    #     target-branch: ${{ inputs.target-branch }}
    #     target-branch-name-surffix: shengwang-sync-auto
    #     pull-request-title: |
    #       [AUTO]sync agora to shengwang>> change package
    #     pull-request-body: |
    #       This is an auto-generated PR to sync agora to shengwang
    #       Please review changes and check the CI status.
    #       If everything is fine, please merge this PR.
